[llvm]
static-libstdcpp = true

[build]
host = ["x86_64-unknown-linux-musl"]
docs = false

[rust]
use-jemalloc = false
codegen-tests = false

[target.x86_64-unknown-linux-musl]
cc = "/musl-x86_64/bin/musl-gcc"
cxx = "/musl-x86_64/bin/musl-g++"
musl-root = "/musl-x86_64"
